### ISSUE TITLE
Avoiding implicit overwrite of "show.signif.stars"

### ISSUE THREAD

**Issue by Yoshinobu-Ishizaki** [emilopezcano/SixSigma#10]
This package is fantastic !
But I have one thing that I would like to ask. 

It would be nice if `ss.rr` does not implicitly overwrite "show.signif.stars". 

Here is my suggestion patch.

Thank you.

[ss-rr-signifstars-patch.txt](https://github.com/emilopezcano/SixSigma/files/6343678/ss-rr-signifstars-patch.txt)

**Comment by emilopezcano** [comment]
Thank you for the suggestion. And apologies for the silence until now.
I am pushing changes with the new argument and your suggested behaviour.

**Comment by Yoshinobu-Ishizaki** [comment]
👍 thank you
